### ISSUE TITLE
API breaks when a valid token is sent when there are no players

### ISSUE THREAD

**Issue by japorized** [Lugarun/salz#25]

**Comment by mosiman** [comment]
I'm 80% sure this is how to repro:

1. Make sure you've `docker-compose down -v` to nuke the database and take down all services. 
2. `docker-compose up` and go to `localhost:8080/login` to retrieve an API token (keep for later step)
3. Upload a test bot, things should work fine. 
4. `docker-compose down -v` to nuke the database
5. Use the same token to upload: API breaks when trying to get playerinfo from the valid token, because the player will not exist in the database. 

We could fix this, or not? because this shouldn't happen if we're not taking down the database. Unfortunately, there's no way to invalidate tokens once they're in the wild. 

One possible solution: If we retrieve a valid token but the player is not in the database, redirect to some front-end endpoint that deletes the token in the localstorage. Maybe just a "oops, something went wrong: try logging in again?" page?

@japorized , thoughts?

**Comment by japorized** [comment]
I think we can make do with a front-end endpoint that will say something like "We need to reconfirm your credentials. Hang on!", and the page will just redirect the user to `/login` on the front end.
